require('dotenv').config();

const { MYSQL_USER, MYSQL_PASSWORD, MYSQL_HOST, MYSQL_PORT } = process.env;

// initial setup generated by sequelize-cli (https://github.com/sequelize/cli);
// modified by me(Andrey Novaes)

module.exports = {
  development: {
    username: MYSQL_USER,
    password: MYSQL_PASSWORD,
    database: 'database_development',
    host: MYSQL_HOST,
    port: MYSQL_PORT,
    dialect: 'mysql',
    define: {
      underscored: true,
      freezeTableName: true,
      charset: 'utf8',
      dialectOptions: {
        collate: 'utf8_general_ci',
      },
    },
  },
  test: {
    username: MYSQL_USER,
    password: MYSQL_PASSWORD,
    database: 'database_test',
    host: MYSQL_HOST,
    port: MYSQL_PORT,
    dialect: 'mysql',
  },
  production: {
    username: MYSQL_USER,
    password: MYSQL_PASSWORD,
    database: 'database_production',
    host: MYSQL_HOST,
    port: MYSQL_PORT,
    dialect: 'mysql',
  },
};
